Flatemate-war/src/java/au/edu/uts/aip/flatmate/web/PostController.java
package au.edu.uts.aip.flatmate.web;

import au.edu.uts.aip.flatmate.domain.ConcurrentException;
import au.edu.uts.aip.flatmate.domain.Customer;
import au.edu.uts.aip.flatmate.domain.FlatMateBean;
import au.edu.uts.aip.flatmate.domain.Post;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * a BackingBean for post(CRUD) views in viewScoped
 * @author weiming
 */
@Named
@ViewScoped
public class PostController extends AbstractController implements Serializable {

    @EJB
    private FlatMateBean flatMateBean;

    private Post currentPost = new Post();
    private Post concurrentModification;
    private List<Post> posts = new ArrayList();

    @Inject
    private AccountController userController;

    /**
     * get a list of posts
     * @return a list of posts
     */
    public List<Post> getPosts() {
        return posts;
    }

    /**
     * an post constructor to initialize the post
     */
    @PostConstruct
    public void init() {
        posts = flatMateBean.findPostsByTopDate();
    }

    /**
     * load the posts ordered by the latest date
     */
    public void loadPostsByLatest() {
        posts = flatMateBean.findPostsByLatest();
    }

    /**
     * retrieve the posts ordered by lowest rent
     */
    public void loadPostsByLowestRent() {
        posts = flatMateBean.findPostsByLowestRent();
    }


    /**
     * load post
     * @param id 
     */
    public void loadPost(int id) {
        currentPost = flatMateBean.findPost(id);
    }

    /**
     * get current post
     * @return currentPost
     */
    public Post getCurrentPost() {
        return currentPost;
    }

    /**
     * get the concurrent modification
     * @return concurrentModification
     */
    public Post getConcurrentModification() {
        return concurrentModification;
    }

    /**
     * set the concurrent modification
     * @param concurrentModification 
     */
    public void setConcurrentModification(Post concurrentModification) {
        this.concurrentModification = concurrentModification;
    }


    /**
     * create a post with automatically setting the date, customer, top date
     * @return myrecord  - turn to my record page
     */
    public String createPost() {
        Date today = new Date();
        currentPost.setDate(today);
        currentPost.setCustomer(userController.getCurrentCustomer());
        currentPost.setTopDate(today);
        flatMateBean.createPost(currentPost);
        return "myrecord?faces-redirect=true";
    }

    /**
     * Updates the post in the database.
     * In the user interface, a concurrent warning is shown when the
     * concurrency exception is caught during updating the post.
     * @return the myrecord.xhtml to show
     *
     * Reference: AIP Week 12 Solution
     */
    public String savePost() {
        try {
            currentPost = flatMateBean.updatePostDetails(currentPost);
            return "myrecord?faces-redirect=true";
        } catch (ConcurrentException ex) {
            concurrentModification = flatMateBean.findPost(currentPost.getId());
            currentPost.setVersion(concurrentModification.getVersion());
            printErrorMessage("This record cannot be updated due to another user is editting at the same time.");
            return null;
        }
    }

    /**
     * delete the post
     * @param id - the id of the post which needs to be deleted
     */
    public void deletePost(int id) {
        flatMateBean.deletePost(id);
    }

    /***
     * Top up the post with the given ID
     * @param id The post id, which is to be topped up
     * @throws ConcurrentException
     */
    public void topPost(int id) throws ConcurrentException {
        Post post = flatMateBean.findPost(id);
        Customer customer = post.getCustomer();

        int points = customer.getPoints();
        if (points > 0) {
            post.setTopDate(new Date());
            customer.setPoints(points - 1);
        } else {
            printErrorMessage("Topup Points is not enough, please upgrade your subscription level.");
        }

        flatMateBean.updatePostDetails(post);
        flatMateBean.updateCustomer(customer);
    }

    /**
     * get all the posts in database
     * @return a list of posts
     */
    public List<Post> getAllPosts() {
        return flatMateBean.findAllPosts();
    }

    /**
     * get the posts are created by current customer
     * @return posts created by current customer
     */
    public List<Post> getMyPosts() {
        return flatMateBean.findPostsByCustomerId(userController.getCurrentCustomer());
    }

}

Flatemate-war/web/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Admin</title>
    </h:head>
    <h:body>
        <b:navBar brand="Flatmate Finder" brandHref="admin.xhtml" inverse="true" fluid="true" >
            <ui:fragment rendered="#{not empty request.remoteUser}">
                <h:form>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><h:link value="G'day, #{request.remoteUser}"></h:link></li>
                            <li><h:commandLink action="#{adminController.logout}" value="Logout"></h:commandLink></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </h:form>
            </ui:fragment>
        </b:navBar>
        <b:container>
            <h1>Admin Dashboard</h1>
            <h:messages styleClass="alert alert-danger" errorStyle="color:red;" infoStyle="color:blue;"/>
            <h:dataTable  class="table table-hover table-fontsize" var="customer" value="#{flatMateController.customers}">
                <h:column>
                    <f:facet name="header">
                        Username
                    </f:facet>
                    <h:link outcome="details" value="#{customer.id}">
                        <f:param name="index" value="#{customer.id}"/>
                    </h:link>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Subscription level
                    </f:facet>
                    <h:outputText value="#{customer.subLevel}"></h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Expiry date
                    </f:facet>
                    <h:outputText value="#{customer.expiryDate}" style="center">
                        <f:convertDateTime pattern="MM/dd/yyyy"/>
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Points
                    </f:facet>
                    <h:outputText value="#{customer.points}" style="center">
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Renew
                    </f:facet>
                    <h:form>
                        <b:commandButton class="btn btn-default btn-sm" value="1 month"
                                         icon="glyphicon glyphicon-repeat" look="success" ajax="false"
                                         rendered="#{accountController.isCustomerSubscribed(customer)}"
                                         action="#{adminController.renew}"/>
                    </h:form>
                </h:column>
            </h:dataTable>
        </b:container>
    </h:body>
</html>

Flatemate-war/web/delete.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        <f:viewAction action="#{postController.loadPost(param.post)}"/>
    </f:metadata>
    <h:head>
        <title>Address Book</title>
    </h:head>
    <h:body>
        <h1>Address Book</h1>
        <h:form>
            <h3>Postal Details</h3>
            <p>
                <label>title:
                    <h:outputText value="#{postController.currentPost.title}"/>
                </label>
            </p>
           <p>
                <label>title:
                    <h:outputText value="#{postController.currentPost.id}"/>
                </label>
            </p>
            
            <p>Are you sure you want to delete this user?</p>
            <p>
                <h:commandButton value="Delete" action="#{postController.deletePost}"/>
                <h:button value="Cancel" outcome="index"/>
            </p>
        </h:form>
    </h:body>
</html>

Flatemate-war/web/details.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <f:metadata>
        <f:viewAction action="#{postController.loadPost(param.post)}"/>
    </f:metadata>
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />
        <div class="container">
            <h1>#{postContorller.title}</h1>
        <br/>
            <div class="row">
                <div class="col-xs-3">
                    <div class="form-group">
                        <label for="suburb" class="control-label">Suburb: </label><br/>
                        <h:outputText class="" value="#{postController.currentPost.suburb}"></h:outputText>
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="form-group">
                        <label for="postcode" class="control-label">Postcode: </label><br/>
                        <h:outputText value="#{postController.currentPost.postcode}"></h:outputText>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-3">
                    <div class="form-group">
                        <label for="type" class="control-label">Type: </label><br/>
                        <h:outputText value="#{postController.currentPost.type}"></h:outputText>
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="form-group">
                        <label for="rent" class="control-label">Rent(AU$): </label><br/>
                        <h:outputText value="#{postController.currentPost.rent}"></h:outputText>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-3">
                    <div class="form-group">
                        <label for="contact" class="control-label">Contact: </label><br/>
                        <h:outputText value="#{postController.currentPost.contact}"></h:outputText>
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="form-group">
                        <label for="email" class="control-label">Email: </label><br/>
                        <h:outputText value="#{postController.currentPost.email}"></h:outputText>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="details">Details: </label><br/>
                <div class='textarea'>
                    <h:outputText value="#{postController.currentPost.detail}"></h:outputText>
                </div>
            </div>
        </div>


    </h:body>
</html>


Flatemate-war/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Error</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />

        <b:container >
            <h1>Whoops</h1>
            <p style="color: red; font-size: x-large">Something went wrong!</p>
            <br/>
            <h:button value="Login" class="btn btn-info"
                      outcome="login"
                      rendered="#{not accountController.logined}"/>
            <span/>
            <b:button value="Back" class="btn btn-info"
                      outcome="index"
                      rendered="#{accountController.logined}"/>
        </b:container>
    </h:body>
</html>

Flatemate-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>home</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />
        <b:container>
            <div class="rightPlus">
                <h1 class='header'>All Posts</h1>
                <h:form>
                    <b:row>
                        <h:button value="Export All Posts" class="btn btn-info bg-primary"
                                  rendered="#{accountController.logined}"
                                  onclick="window.open('#{accountController.restBaseUri}' + 'all')">
                        </h:button>
                        <span/>
                        <b:commandButton value="Filter By Lastest" look="info"
                                         rendered="#{accountController.logined and accountController.subscribed}"
                                         action="#{postController.loadPostsByLatest}" />
                        <span/>
                        <b:commandButton value="Filter By Lowest Rent" look="info"
                                         rendered="#{accountController.logined and accountController.subscribed}"
                                         action="#{postController.loadPostsByLowestRent}" />
                    </b:row>
                </h:form>
            </div>

            <br/>
            <h:dataTable  class="table table-hover table-fontsize" var="post" value="#{postController.posts}">
                <h:column>
                    <f:facet name="header">
                        PostId
                    </f:facet>
                    <h:outputText value="#{post.id}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Title
                    </f:facet>
                    <h:link outcome="details" value="#{post.title}">
                        <f:param name="post" value="#{post.id}"/>
                    </h:link>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Details
                    </f:facet>
                    <h:outputText value="#{post.detail}">
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Rent
                    </f:facet>
                    <h:outputText value="#{post.rent}">
                        <f:convertNumber currencySymbol="$" type="currency"/>
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Location
                    </f:facet>
                    <h:outputText value="#{post.suburb}">
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Publish Date
                    </f:facet>
                    <h:outputText value="#{post.date}">
                        <f:convertDateTime pattern="dd/MM/yyyy"/>
                    </h:outputText>
                </h:column>
                <!--                <h:column>
                                    <f:facet name="header">
                                        Top Date
                                    </f:facet>
                                    <h:outputText value="#{post.topDate}">
                                        <f:convertDateTime pattern="dd/MM/yyyy"/>
                                    </h:outputText>
                                </h:column>-->
                <h:column>
                    <f:facet name="header">
                        Publisher
                    </f:facet>
                    <h:outputText value="#{post.customer.id}"/>
                </h:column>
            </h:dataTable>
        </b:container>
    </h:body>
</html>

Flatemate-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Login</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />

        <b:container >
            <h1>Login</h1>
            <b:tabView activeIndex="0">
                <b:tab title="Login">
                    <h3>Login</h3>

                    <h:panelGrid cellpadding="3" >
                        <h:form>
                            <h:panelGrid cellpadding="5" >
                                <b:inputText required="true" placeholder="username"
                                             id="username" requiredMessage="Please enter the username"
                                             value="#{accountController.inputId}" >
                                    <f:facet name="prepend">
                                        <b:icon name="user"/>
                                    </f:facet>
                                </b:inputText>
                                <b:inputSecret required="true" placeholder="password"
                                               id="password" requiredMessage="Please enter the password"
                                               value="#{accountController.inputPassword}">
                                    <f:facet name="prepend">
                                        <b:icon name="lock"/>
                                    </f:facet>
                                </b:inputSecret>
                            </h:panelGrid>
                            <h:messages styleClass="alert alert-danger" style="color: red;"/>
                            <b:commandButton value="Login" look="primary" action="#{accountController.login}" />
                        </h:form>
                    </h:panelGrid>
                </b:tab>

                <!--this function does not finish yet-->
                <b:tab title="Login as Admin">
                    <h3>Login as Admin</h3>
                    <h:form >
                        <h:panelGrid cellpadding="5" >
                            <b:inputText required="true" placeholder="username"
                                         id="username" requiredMessage="Please enter the username"
                                         value="#{adminController.admin.username}" >
                                <f:facet name="prepend">
                                    <b:icon name="user"/>
                                </f:facet>
                            </b:inputText>
                            <b:inputSecret required="true" placeholder="password"
                                           id="password" requiredMessage="Please enter the password"
                                           value="#{adminController.admin.password}">
                                <f:facet name="prepend">
                                    <b:icon name="lock"/>
                                </f:facet>
                            </b:inputSecret>
                        </h:panelGrid>
                        <h:messages styleClass="alert alert-danger" style="color: red;"/>
                        <b:commandButton value="Login" look="primary" action="#{adminController.login}" />
                    </h:form>
                </b:tab>
            </b:tabView>
        </b:container>
    </h:body>
</html>


Flatemate-war/web/myrecord.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>my record</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />

        <b:container>
            <div class="rightPlus">
                <h1 class='header'>My Record</h1>
                <b:button class="btn btn-info btn-lg" value="Create"
                          outcome="post" look="info" icon="glyphicon glyphicon-edit">
                </b:button>
                <span></span>
                <h:button class="btn btn-info btn-lg" value="Export"
                          onclick="window.open('#{accountController.restBaseUri}' + '#{request.remoteUser}')"/>
            </div>
            <br></br>

            <h:dataTable columnClasses="column1,column2,column3,column4,column5"
                         class="table table-hover table-fontsize"
                         var="post" value="#{postController.myPosts}">
                <h:column>
                    <f:facet name="header">
                        PostId
                    </f:facet>
                    <h:outputText value="#{post.id}"></h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Title
                    </f:facet>
                    <h:outputText value="#{post.title}"></h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Location
                    </f:facet>
                    <h:outputText value="#{post.suburb}"></h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Publisher
                    </f:facet>
                    <h:outputText value="#{post.customer.id}"></h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Publish Date
                    </f:facet>
                    <h:outputText value="#{post.date}">
                        <f:convertDateTime pattern="dd/MM/yyyy"/>
                    </h:outputText>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Edit
                    </f:facet>
                    <b:button class="btn btn-default btn-sm" icon="glyphicon glyphicon-pencil" outcome="update" value="">
                        <f:param name="post" value="#{post.id}"/>
                    </b:button>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Delete
                    </f:facet>
                    <h:form>
                        <h:commandLink class="btn btn-default btn-sm"
                                       action="#{postController.deletePost(post.id)}" value="">
                            <span class="glyphicon glyphicon-trash"/>
                        </h:commandLink>
                    </h:form>
                </h:column>
                <h:column rendered="#{accountController.subscribed}">
                    <f:facet name="header">
                        Top
                    </f:facet>
                    <h:form>
                        <h:commandLink class="btn btn-default btn-sm"
                                       action="#{postController.topPost(post.id)}" value="">
                            <span class="glyphicon glyphicon-arrow-up"/>
                        </h:commandLink>
                    </h:form>
                </h:column>
            </h:dataTable>
            <h:messages styleClass="alert alert-danger" errorStyle="color:red;" infoStyle="color:blue;"/>
        </b:container>
    </h:body>
</html>


Flatemate-war/web/navbar.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">
    <b:navBar brand="Flatmate Finder" brandHref="index.xhtml" inverse="true" fluid="true" >

        <ui:fragment rendered="#{empty request.remoteUser}">
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><h:link value="Register" outcome="register"></h:link></li>
                    <li><h:link value="Login" outcome="login"></h:link></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </ui:fragment>
        <ui:fragment rendered="#{not empty request.remoteUser}">
            <h:form>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><h:link value="G'day, #{request.remoteUser}"></h:link></li>
                    <li><h:link value="My Record" outcome="myrecord"></h:link></li>
                    <li><h:link value="Profile" outcome="profile"></h:link></li>
                    <li><h:commandLink action="#{accountController.logout}" value="Logout"></h:commandLink></li>
                </ul>
            </div><!-- /.navbar-collapse -->
            </h:form>
        </ui:fragment>
    </b:navBar>
</ui:composition>

Flatemate-war/web/payment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />
        <div class="container">
            <h1>Payment</h1>
            <b>You are going to pay: AU$5.</b>

            <h:form>
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <br/>
                            <label for="details">Credit Card </label>
                            <b:inputText placeholder="5625 3335 3322 1111" class="form-control form-width"  required="true" value="#{postContorller.title}" requiredMessage="Please enter the title"></b:inputText>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <h:messages errorStyle="color:red;" infoStyle="color:blue;"/>
                    <b:commandButton value="Submit" look="primary" action="#{postContorller.saveAsNew}" />
                </div>
            </h:form>
        </div>
    </h:body>
</html>


Flatemate-war/web/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Profile Setting</title>
    </h:head>
    <h:body>
        <ui:include src="navbar.xhtml" />
        <b:container >
            <h1>Profile</h1>
            <b:tabView activeIndex="0">
                <b:tab title="My plan">
                    <h:panelGrid cellpadding="3" >
                        <h:form>
                            <h3>Member type</h3>
                            <h:outputText value="Current state: #{accountController.currentCustomer.subLevel}"></h:outputText>
                            <b:selectOneMenu value="#{accountController.currentCustomer.subLevel}" >
                                <f:selectItem itemValue="FREE" itemLabel="Free - $0" />
                                <f:selectItem itemValue="STANDARD" itemLabel="Standard - $5/month" />
                                <f:selectItem itemValue="PREMIUM" itemLabel="Premium - $7/month" />
                            </b:selectOneMenu>
                            <h:messages styleClass="alert alert-danger" errorStyle="color:red;" infoStyle="color:blue;"/>
                            <b:commandButton value="Change" look="primary" action="#{accountController.changePlan}"/>
                        </h:form>
                    </h:panelGrid>
                </b:tab>


            </b:tabView>
        </b:container>
    </h:body>
</html>
